sudo: required
services:
 - docker
 before_install:
  - docker build -t Ayushkumar047/react-test -f ./client/Dockerfile.dev ./client
 script:
  - docker run -t Ayushkumar047/react-test npm test -- --coverage
 after_success:
  - docker build -t Ayushkumar047/multi-client ./client
  - docker build -t Ayushkumar047/multi-nginx ./nginx
  - docker build -t Ayushkumar047/multi-server ./server
  - docker build -t Ayushkumar047/multi-worker ./worker
  # log in docker hub
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to docker hub
  - docker push Ayushkumar047/multi-client
  - docker push Ayushkumar047/multi-nginx
  - docker push Ayushkumar047/multi-server
  - docker push Ayushkumar047/multi-worker

