sudo: required
services:
 - docker
before_install:
 - docker build -t ayushkumar047/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run -t ayushkumar047/react-test npm test -- --coverage
after_success:
 - docker build -t ayushkumar047/multi-client ./client
 - docker build -t ayushkumar047/multi-nginx ./nginx
 - docker build -t ayushkumar047/multi-server ./server
 - docker build -t ayushkumar047/multi-worker ./worker
<<<<<<< HEAD
 # log in docker hub
 - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # push image to docker hub
=======
# log in docker hub
 - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push image to docker hub
>>>>>>> 62a98e7df2e61671dafda19a9e0a85eb5ffa90bc
 - docker push ayushkumar047/multi-client
 - docker push ayushkumar047/multi-nginx
 - docker push ayushkumar047/multi-server
 - docker push ayushkumar047/multi-worker
